apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    app: mydep
spec:
   replicas: 1
   selector:
      matchLabels:
        app: mydep
   template:
     metadata:
       labels:
         app: mydep
     spec:
       containers:
         - name: nginx
           image: vinayadav99/newapp:mtag
           ports:
             - containerPort: 80



---

apiVersion: v1
kind: Service
metadata:
  name: mydep 
  labels:
    app: mydep
spec: 
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30124
  selector:
    app: mydep
  type: NodePort

